
module.exports = {
    folder_app: 'app',
    folder_configs: 'configs',
    folder_helpers: 'helpers',
    folder_routers: 'routes',
    folder_schemas: 'schemas',
    folder_controllers: 'controllers',
    folder_controllersAPI: 'controllersAPI',
    folder_models: 'models',
    folder_validates: 'validates',
    folder_middleware: 'middleware',
    folder_views: 'views',
    folder_module_admin: 'admin',
    folder_module_apiadmin: 'api',
    folder_module_openapi: 'openapi',
    folder_module_blog: 'blog',
    folder_module_chat: 'chat',
    folder_public: 'public',
    folder_uploads: 'uploads',
    folder_views_backend: 'views/admin',
    folder_templateExport: 'public/template',
    folder_language: 'languages',
    folder_ca: 'ca',
};