let schemas = {
	table: 'sys_users',
	primaryKeyColumn: 'id',
	id: 'int',
	employee_code: 'string',
	company_id: 'int',
	department_id: 'int',
	position_id: 'int',
	firstname: 'string',
	lastname: 'string',
	username: 'string',
	username_encrypted: 'string',
	password: 'string',
	birthday: 'DateTime',
	sex: 'string',
	email: 'string',
	phonenumber: 'string',
	address: 'string',
	district: 'Int64',
	provincial: 'Int64',
	nation: 'string',
	is_management: 'int',
	status: 'string',
	last_time_login: 'DateTime',
	avatar: 'string',
	receive_email: 'int',
	receive_sms: 'int',
	full_path_temporary_save: 'string',
	temporary_file_name: 'string',
	path_temporary_save: 'string',
	manager_code: 'Int64',
	link_change_password: 'string',
	token_change_password: 'string',
	notification_time_changed_password: 'DateTime',
	time_changed_password: 'DateTime',
	browser_headers: 'string',
	is_status_login: 'byte',
	user_id_created: 'int',
	user_name_created: 'string',
	datetime_created: 'DateTime',
	user_id_modified: 'int',
	user_name_modified: 'string',
	datetime_modified: 'DateTime',
};
module.exports = {
	schemas
};
