
module.exports = {
    CHANGE_STATUS_SUCCESS: 'Updated status successfully',
    CHANGE_SPECIAL_SUCCESS: 'Special update successful',
    CHANGE_STATUS_MULTI_SUCCESS: 'There are %d elements whose status has been successfully updated',
    CHANGE_GROUP_ACP_SUCCESS: 'Update Group ACP successfully',
    CHANGE_GROUP_SUCCESS: 'Group updated successfully',
    CHANGE_ORDERING_SUCCESS: 'Ordering update successful',
    CHANGE_ORDERING_ERROR: 'Error while updating ordering',
    DELETE_SUCCESS: 'Deleted element successfully',
    DELETE_MULTI_SUCCESS: 'There are %d elements successfully deleted',
    ADD_SUCCESS: 'New element added successfully',
    ADD_ERROR: 'Adding new element failed, please check your permissions',
    EDIT_SUCCESS: 'Update element information successfully',
    EDIT_ERROR: 'Updating element information failed, please check your permissions',
    ERROR_NAME: 'Length from %d to %d characters',
    ERROR_STRING: 'Length from %d to %d characters',
    ERROR_NUMBER: 'Must be a number between %d and %d ',
    ERROR_NUMBER_INT: 'Must be an integer between %d and %d ',
    ERROR_ORDERING: 'Must be an integer greater than %d and less than %d',
    ERROR_STATUS: 'Must be a non-empty value',
    ERROR_SPECIAL: 'Must be a non-empty value',
    ERROR_GROUP: 'Must be a non-empty value',
    ERROR_GROUPACP: 'Must be a non-empty value',
    ERROR_FILE_REQUIRE: 'Please select file to upload',
    ERROR_FILE_LIMIT: 'File size does not match',
    ERROR_FILE_EXTENSION: 'Invalid file extension',
    ERROR_LOGIN: 'Username or password is incorrect',
    ERROR_LOGIN_PASSWORD_INCORRECT: 'Password is incorrect',
    ERROR_LOGIN: 'Login information is incorrect',
    ERROR_DELETE: 'Delete failed, If there are details, please delete the details first!',
    ERROR_MSG_CHAT_TOO_SHORT: 'Message length is too short',
    
};